target:
    apiVersion: kubernetes.openmcf.org/v1
    kind: KubernetesRedis
    metadata:
        env: gcp-dev
        labels:
            kubernetes.openmcf.org/context: gke_planton-shared-kfn_asia-south1_gcp-shared-cluster
            openmcf.org/provisioner: pulumi
            pulumi.openmcf.org/organization: organization
            pulumi.openmcf.org/project: planton
            pulumi.openmcf.org/stack.name: gcp-dev.KubernetesRedis.redis-test-stack-input-1
        name: redis-test-stack-input-1
        org: planton
    spec:
        container:
            diskSize: 5Gi
            persistenceEnabled: true
            replicas: 1
            resources:
                limits:
                    cpu: 1000m
                    memory: 2Gi
                requests:
                    cpu: 100m
                    memory: 256Mi
        createNamespace: true
        ingress: {}
        namespace:
            value: redis-test-stack-input-1
